# Generated by Django 5.0 on 2024-08-19 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rent_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('borrowed', 'Borrowed')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
