# Generated by Django 5.0 on 2024-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(blank=True, choices=[('available', 'Available'), ('rented', 'Rented'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
