# Generated by Django 5.0 on 2024-08-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_book_author_image_alter_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
